name: Lint dockerfile 
on: 
 push: 
   branches:
     - sample
 pull_request:
   branches:
     - main
 workflow_dispatch:
 
jobs:
 test:
   uses: saiteja-organization/test1/.github/workflows/main.yml@testing
   with:
      workflow_id: py-lint.yml
      files_to_match: \.(py|pyc)$
   secrets:
      gh_token: ${{ secrets.gh_token }} 
      
